language: scala

scala:
  - 2.11.11
  - 2.12.4

jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

before_script: unset SBT_OPTS

script: sbt clean test

after_script:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success: bash <(curl -s https://codecov.io/bash)
